apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/uditmishra03/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git
    targetRevision: master
    path: k8s-infrastructure
    directory:
      include: ingress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: three-tier
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
